name: Build Canary

on:
  push:
    branches:
      - '**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Versioning
      - name: Extract commit short sha
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Create Canary Version File
        run: |
          rm -f Profile\ Folder/chrome/version.json
          echo '{
            "version": "${{ env.COMMIT_SHORT_SHA }}",
            "update_channel": "canary",
            "branch": "${{ steps.extract_branch.outputs.branch }}"
          }' > Profile\ Folder/chrome/version.json
      # Setup the SASS command
      - name: Setup SASS
        run: npm install -g sass
      # Actual building
      - name: Compile CSS from SCSS files
        run: sass --update Profile\ Folder/chrome:Profile\ Folder/chrome
      - name: Cleanup the build output
        run: rm -rf .github .gitignore 
      - name: Archive the build
        uses: actions/upload-artifact@v4
        with:
          name: Geckium Canary Build ${{ env.COMMIT_SHORT_SHA }}
          path: .