name: Build Canary

on:
  push:
    branches:
      - '**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Versioning
      - name: Extract commit short sha
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Create Canary Version File
        run: |
          rm -f Profile\ Folder/chrome/version.json
          echo '{
            "version": "${{ env.COMMIT_SHORT_SHA }}",
            "update_channel": "canary",
            "branch": "${{ steps.extract_branch.outputs.branch }}"
          }' > Profile\ Folder/chrome/version.json

      # Actual building
      - name: Compile CSS from SCSS files
        run: sass --watch Profile\ Folder/chrome:Profile\ Folder/chrome
        
      - name: See if we actually compiled the CSS
        run: ls -la Profile\ Folder/chrome
